name: Print all sorts of hashes

on:
  [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: echo before hash ${{ github.event.before || github.event.pull_request.base.sha }} || $(git log --pretty=%P -n 1 ${{ github.event.after }})
    - run: echo after hash ${{ github.event.after }}
    - run: echo github.event.before ${{ github.event.before }}, github.event.after ${{ github.event.after }}
