name: Print all sorts of hashes

on:
  [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"        
    - run: echo github.event.before ${{ github.event.before }}, github.event.pull_request.base.sha ${{ github.event.pull_request.base.sha }}
