# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, closed]
#   schedule: 
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '*/15 * * * *'   # Runs every 15 mins
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:

  cwe22:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout the action from a private repository
      uses: actions/checkout@v2
      continue-on-error: true
      with:
        repository: vijejain/cicd-actions
        ref: refs/heads/main
        token: ${{ secrets.PAT_TOKEN }}
        path: ./.github/vijejain/cicd-actions

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: AWS CodeGuru Reviewer
      uses: ./.github/vijejain/cicd-actions 
      continue-on-error: true
      with:          
        name: cicd-repo-2
        source_path: ./
        build_path: ./owasp-benchmark/by_cwe_jars/owasp-cwe022-only.jar

  cwe78:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout the action from a private repository
      uses: actions/checkout@v2
      continue-on-error: true
      with:
        repository: vijejain/cicd-actions
        ref: refs/heads/main
        token: ${{ secrets.PAT_TOKEN }}
        path: ./.github/vijejain/cicd-actions

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: AWS CodeGuru Reviewer
      uses: ./.github/vijejain/cicd-actions 
      continue-on-error: true
      with:          
        name: cicd-repo-2
        source_path: ./
        build_path: ./owasp-benchmark/by_cwe_jars/owasp-cwe078-only.jar

  cwe79:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout the action from a private repository
      uses: actions/checkout@v2
      continue-on-error: true
      with:
        repository: vijejain/cicd-actions
        ref: refs/heads/main
        token: ${{ secrets.PAT_TOKEN }}
        path: ./.github/vijejain/cicd-actions

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2    
    - name: AWS CodeGuru Reviewer
      uses: ./.github/vijejain/cicd-actions 
      continue-on-error: true
      with:          
        name: cicd-repo-2
        source_path: ./
        build_path: ./owasp-benchmark/by_cwe_jars/owasp-cwe079-only.jar

  upload_sarif:
    runs-on: ubuntu-latest
    needs: 
      - cwe22
      - cwe78
      - cwe79
    steps:
    - name: Upload review result
      continue-on-error: true
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeguru-results.sarif.json
