name: Run CodeGuru on OWASP Benchmark

on:
  push:
    branches: [ main, submodule ]
  pull_request:
    branches: [ main, submodule ]
    types: [opened, closed]
#   schedule: 
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '*/15 * * * *'   # Runs every 15 mins
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'info'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:
    name: Build and cache OWASP Jars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'true'
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and package
      run: ./create_jars.sh
    - name: Store jars
      uses: actions/upload-artifact@v2
      with:
        name: analyzed_jars
        path: ./by-cwe

  cwes:
    name: Analyze Jar files
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        include:
          - cwe: cwe022
          - cwe: cwe078
          - cwe: cwe079
          - cwe: cwe089
          - cwe: cwe090
          - cwe: cwe327
          - cwe: cwe328
          - cwe: cwe614
          - cwe: cwe643
    steps:

    - name: Checkout the code and submodules
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'true'


    # Extra step requied for BugBash
    - name: Checkout the action from a private repository
      uses: actions/checkout@v2
      if: ${{ always() }}
      with:
        repository: vijejain/cicd-actions-bugbash
        ref: refs/heads/main
        token: ${{ secrets.PAT }}
        path: ./.github/vijejain/cicd-actions-bugbash

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        
    # Download the artifacts AFTER the checkout, otherwise the git checkout will override the
    # content of this folder.
    - name: Download all aritfacts
      uses: actions/download-artifact@v2
      with:
        name: analyzed_jars
        path: ./analyzed_jars
    - name: Cached Jars 2
      run: |        
        ls -R ./analyzed_jars
      working-directory: ./      

    - name: AWS CodeGuru Reviewer
      uses: ./.github/vijejain/cicd-actions-bugbash
      continue-on-error: true
      with:          
        s3_bucket: codeguru-reviewer-github-submodule
        build_path: ./analyzed_jars/${{ matrix.cwe }}
        
    - run: |
        mkdir ./${{ matrix.cwe }}_findings
        cp ./*.json ./${{ matrix.cwe }}_findings || true
    - name: Store Findings
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.cwe }}_findings
        path: ./${{ matrix.cwe }}_findings

  upload_sarif:
    name: Merge findings for all Jars and create Scorecard
    runs-on: ubuntu-latest
    needs: 
      - cwes
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'true'
    # Download the artifacts AFTER the checkout, otherwise the git checkout will override the
    # content of this folder.
    - name: Download all aritfacts
      uses: actions/download-artifact@v2
      id: download_findings
      with:
        path: ./     
    - name: Display structure of downloaded files
      run: ls -R cwe*
      working-directory: ./     

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: "Create Scorecard"
      run: ./createScorecard.sh
    - name: Store Merged Findings For Debugging
      uses: actions/upload-artifact@v2
      with:
        name: merged_findings
        path: ./owasp-benchmark/results
    - name: Store Findings
      uses: actions/upload-artifact@v2
      with:
        name: scorecard
        path: ./owasp-benchmark/scorecard
    - name: "Copy scorecard"
      run: | 
        cp -r ./owasp-benchmark/scorecard ./html
        cp html/Benchmark_v1.2_Scorecard_for_AWS_CodeGuru_Reviewer.html html/index.html
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: html # The folder the action should deploy.
