name: Run CodeGuru on OWASP Benchmark

on:
  push:
    branches: [ sarif ]
  pull_request:
    branches: [ sarif ]
    types: [opened, closed]
#   schedule: 
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '*/15 * * * *'   # Runs every 15 mins
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'info'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:
    name: Build and cache OWASP Jars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload review result
      continue-on-error: true
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ./codeguru-results.sarif.json