# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, closed]
#   schedule: 
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '*/15 * * * *'   # Runs every 15 mins
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout the action from a private repository
      uses: actions/checkout@v2
      continue-on-error: true
      with:
        repository: vijejain/cicd-actions
        ref: refs/heads/main
        token: ${{ secrets.PAT_TOKEN }}
        path: ./.github/vijejain/cicd-actions
    - name: Build and package
      run: ./create_jars.sh	
    - name: Cache source and build files for subsequent jobs
      uses: actions/cache@v2
      with:
        path: |
          ./.github/vijejain/        
          ./owasp-benchmark/src
          ./by-cwe
          ./.git
        key: ${{ runner.os }}-artifacts

  cwe22:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Cache source and build files for subsequent jobs
      uses: actions/cache@v2
      with:
        path: |
          ./.github/vijejain/
          ./owasp-benchmark/src
          ./by-cwe
          ./.git
        key: ${{ runner.os }}-artifacts
    - run: echo "Total java files $(find owasp-benchmark/src/main/java -type f -name '*.java' | wc -l )"
    - run: echo "Total class files $(find ./by-cwe/cwe022 -type f -name '*.class' | wc -l )"
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: AWS CodeGuru Reviewer
      uses: ./.github/vijejain/cicd-actions 
      continue-on-error: true
      with:          
        name: cicd-repo-2
        source_path: ./
        build_path: ./by-cwe/cwe022
    - run: |
        mkdir ./cwe22-findings
        cp /github/workspace/codeguru-results.json ./cwe022-findings/codeguru-results.json
        cp ./codeguru-results.sarif.json ./cwe022-findings/codeguru-results.sarif.json
    - name: Store Findings
      uses: actions/upload-artifact@v2
      with:
        name: cwe022_findings
        path: ./cwe022-findings

  cwe78:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Cache source and build files for subsequent jobs
      uses: actions/cache@v2
      with:
        path: |
          ./.github/vijejain/        
          ./owasp-benchmark/src
          ./by-cwe
          ./.git
        key: ${{ runner.os }}-artifacts
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: AWS CodeGuru Reviewer
      uses: ./.github/vijejain/cicd-actions 
      continue-on-error: true
      with:          
        name: cicd-repo-2
        source_path: ./
        build_path: ./by-cwe/cwe078
    - run: |
        mkdir ./cwe78-findings
        cp /github/workspace/codeguru-results.json ./cwe078-findings/codeguru-results.json
        cp ./codeguru-results.sarif.json ./cwe078-findings/codeguru-results.sarif.json
    - name: Store Findings
      uses: actions/upload-artifact@v2
      with:
        name: cwe078_findings
        path: ./cwe078-findings

  cwe79:
    runs-on: ubuntu-latest
    needs: build    
    steps:
    - name: Cache source and build files for subsequent jobs
      uses: actions/cache@v2
      with:
        path: |
          ./.github/vijejain/        
          ./owasp-benchmark/src
          ./by-cwe
          ./.git
        key: ${{ runner.os }}-artifacts

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2    
    - name: AWS CodeGuru Reviewer
      uses: ./.github/vijejain/cicd-actions 
      continue-on-error: true
      with:          
        name: cicd-repo-2
        source_path: ./
        build_path: ./by-cwe/cwe079
    - name: Store Findings
      uses: actions/upload-artifact@v2
      with:
        name: cwe079_findings
        path: ./codeguru-results.sarif.json
        
  upload_sarif:
    runs-on: ubuntu-latest
    needs: 
      - cwe22
      - cwe78
      - cwe79
    steps:
    - name: Download CWE22 Findings 
      uses: actions/download-artifact@v2
      with:
        name: cwe022_findings

    - name: Upload review result
      continue-on-error: true
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ./cwe022-findings/codeguru-results.sarif.json
